apiVersion: v2
name: keycloak-config-cli
description: Import JSON-formatted configuration files into Keycloak - Configuration as Code for Keycloak.
home: https://github.com/adorsys/keycloak-config-cli
version: 6.1.0
appVersion: 6.1.0
maintainers:
  - name: jkroepke
    email: joe@adorsys.de
    url: https://github.com/jkroepke
keywords:
  - keycloak
  - config
  - import
  - json
  - continuous-integration
  - keycloak-config-cli
sources:
  - https://github.com/adorsys/keycloak-config-cli
